---
- name: check if custom template for prod.secret.exs exists
  local_action: stat path="templates/prod.secret.exs.j2"
  register: custom_prod_secret_template


- when: custom_prod_secret_template.stat.exists == False
  name: add prod.secret.exs from default template
  template:
    src: default-prod.secret.exs.j2
    dest: "{{ project_path }}/config/prod.secret.exs"
  become: "{{primary_user_sudo}}"
  become_user: "{{ deploy_user }}"


- when: custom_prod_secret_template.stat.exists == True
  name: add prod.secret.exs from custom template provided
  template:
    src: templates/prod.secret.exs.j2
    dest: "{{ project_path }}/config/prod.secret.exs"
  become: "{{primary_user_sudo}}"
  become_user: "{{ deploy_user }}"
